/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.eclipse.jetty:jetty-servlet:9.0.3.v20130506")
    implementation("commons-io:commons-io:2.4")
    implementation("net.sf.opencsv:opencsv:2.0")
    implementation("com.beust:jcommander:1.30")
}

group = "com.sk89q"
version = "1.0.0-SNAPSHOT"
description = "WarmRoast"
java.sourceCompatibility = JavaVersion.VERSION_1_7

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
