/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.eclipse.jetty:jetty-servlet:9.0.3.v20130506")
    implementation("commons-io:commons-io:2.4")
    implementation("net.sf.opencsv:opencsv:2.0")
    implementation("com.beust:jcommander:1.30")
}

group = "com.sk89q"
version = "1.0.0-SNAPSHOT"
description = "WarmRoast"
java.sourceCompatibility = JavaVersion.VERSION_17

tasks {
    compileJava {
        options.encoding = "UTF-8"
        sourceCompatibility = "17"
    }
    compileTestJava {
        options.encoding = "UTF-8"
        sourceCompatibility = "17"
    }
    jar {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        configurations["compileClasspath"].forEach { file: File ->
            from(zipTree(file.absoluteFile)) {
                exclude("META-INF/*.RSA", "META-INF/*.SF", "META-INF/*.DSA")
            }
        }
    }
}
